# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Turing Simulator
email: paul.brunet@u-pec.fr
description: Simulateur de machines de Turing
baseurl: "/machine-simulator" # the subpath of your site, e.g. /blog
url: "https://monstrencage.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  monstrencage
github: [metadata]

# Build settings
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-email-protect
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

atom_feed:
  hide: true

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale: fr-FR

logo: assets/images/turing.png

author:
  name: Paul Brunet
  avatar: assets/images/tronche.jpg
  location: Créteil, France
  links:
  - label: "dblp"
    icon: "ai ai-dblp"
    url: "http://www.informatik.uni-trier.de/~ley/pers/hd/b/Brunet:Paul.html"
  - label: "google scholar"
    icon: "ai ai-google-scholar"
    url: "http://scholar.google.fr/citations?user=PQKwjzAAAAAJ"
  - label: "research gate"
    icon: "ai ai-researchgate"
    url: "http://www.researchgate.net/profile/Paul_Brunet2"
  - label: "orcid"
    icon: "ai ai-orcid"
    url: "https://orcid.org/0000-0002-9762-6872"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  machines:
    output: true

defaults:
  -
    scope:
      path: ''
      type: "machines"
    values:
      layout: machines
